name: trialgeo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: 4.6.6

  geocoding: ^3.0.0
  geolocator: ^11.1.0
  clipboard: ^0.1.3
  permission_handler: ^9.2.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

